name: thermostat_check
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # QRコードとOCR
  mobile_scanner: ^5.1.0
  google_mlkit_text_recognition: ^0.15.0
  camera: ^0.11.0 # ★ OCR機能のために再度追加

  # その他
  permission_handler: ^11.4.0
  http: ^1.2.0
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
